version: '3.9'

services:
  backend:
    build:
      context: ./prod_server
      dockerfile: Dockerfile.backend
    volumes:
      - ./My Celtic Calendar App:/app
    ports:
      - "8000:8000"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "8080:80"
    depends_on:
      - backend