# Stage 1: Build Vite app
FROM node:18-slim AS builder
WORKDIR /app
COPY . .

# Prevent NPM from crashing due to optional deps
ENV NODE_OPTIONS=--openssl-legacy-provider

RUN npm install --legacy-peer-deps
RUN npm run build

# Stage 2: Serve with Nginx
FROM nginx:stable-alpine
COPY ./nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/static /usr/share/nginx/html